coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: 90%
        threshold: 2%
comment:
  layout: "reach, diff, flags, files"
  require_changes: false
  behavior: default
