# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mcp_pb2 as mcp__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mcp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class McpServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/mcp.McpService/Health',
                request_serializer=mcp__pb2.HealthRequest.SerializeToString,
                response_deserializer=mcp__pb2.HealthStatus.FromString,
                _registered_method=True)
        self.Query = channel.unary_stream(
                '/mcp.McpService/Query',
                request_serializer=mcp__pb2.QueryRequest.SerializeToString,
                response_deserializer=mcp__pb2.QueryResult.FromString,
                _registered_method=True)
        self.UpsertNodes = channel.unary_unary(
                '/mcp.McpService/UpsertNodes',
                request_serializer=mcp__pb2.UpsertNodesRequest.SerializeToString,
                response_deserializer=mcp__pb2.Ack.FromString,
                _registered_method=True)
        self.UpsertEdges = channel.unary_unary(
                '/mcp.McpService/UpsertEdges',
                request_serializer=mcp__pb2.UpsertEdgesRequest.SerializeToString,
                response_deserializer=mcp__pb2.Ack.FromString,
                _registered_method=True)
        self.UpsertHyperedges = channel.unary_unary(
                '/mcp.McpService/UpsertHyperedges',
                request_serializer=mcp__pb2.UpsertHyperedgesRequest.SerializeToString,
                response_deserializer=mcp__pb2.Ack.FromString,
                _registered_method=True)


class McpServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertEdges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertHyperedges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_McpServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=mcp__pb2.HealthRequest.FromString,
                    response_serializer=mcp__pb2.HealthStatus.SerializeToString,
            ),
            'Query': grpc.unary_stream_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=mcp__pb2.QueryRequest.FromString,
                    response_serializer=mcp__pb2.QueryResult.SerializeToString,
            ),
            'UpsertNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertNodes,
                    request_deserializer=mcp__pb2.UpsertNodesRequest.FromString,
                    response_serializer=mcp__pb2.Ack.SerializeToString,
            ),
            'UpsertEdges': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertEdges,
                    request_deserializer=mcp__pb2.UpsertEdgesRequest.FromString,
                    response_serializer=mcp__pb2.Ack.SerializeToString,
            ),
            'UpsertHyperedges': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertHyperedges,
                    request_deserializer=mcp__pb2.UpsertHyperedgesRequest.FromString,
                    response_serializer=mcp__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mcp.McpService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mcp.McpService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class McpService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.McpService/Health',
            mcp__pb2.HealthRequest.SerializeToString,
            mcp__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mcp.McpService/Query',
            mcp__pb2.QueryRequest.SerializeToString,
            mcp__pb2.QueryResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.McpService/UpsertNodes',
            mcp__pb2.UpsertNodesRequest.SerializeToString,
            mcp__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertEdges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.McpService/UpsertEdges',
            mcp__pb2.UpsertEdgesRequest.SerializeToString,
            mcp__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertHyperedges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.McpService/UpsertHyperedges',
            mcp__pb2.UpsertHyperedgesRequest.SerializeToString,
            mcp__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
